/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CargoType = 'Containerized' | 'InBulk' | 'AsLooseGoods';

export const CargoType = {
    Containerized: 'Containerized' as CargoType,
    InBulk: 'InBulk' as CargoType,
    AsLooseGoods: 'AsLooseGoods' as CargoType
};