/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dimensions } from './dimensions';
import { VolumeUnit } from './volumeUnit';
import { WeightUnit } from './weightUnit';

export interface CargoSpecifications { 
    dimensions?: Dimensions;
    volume?: number;
    volumeUnit?: VolumeUnit;
    weight?: number;
    weightUnit?: WeightUnit;
}