/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CargoSpecifications } from './cargoSpecifications';
import { ContainerLength } from './containerLength';
import { ContainerLoadingMode } from './containerLoadingMode';
import { ContainerType } from './containerType';

export interface Container { 
    amount?: number;
    type?: ContainerType;
    length?: ContainerLength;
    loadingMode?: ContainerLoadingMode;
    specifications?: CargoSpecifications;
}