/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContainerType = 'Standard' | 'OpenTop' | 'FlatRack' | 'Reefer' | 'Tank' | 'Ventilated' | 'Platform';

export const ContainerType = {
    Standard: 'Standard' as ContainerType,
    OpenTop: 'OpenTop' as ContainerType,
    FlatRack: 'FlatRack' as ContainerType,
    Reefer: 'Reefer' as ContainerType,
    Tank: 'Tank' as ContainerType,
    Ventilated: 'Ventilated' as ContainerType,
    Platform: 'Platform' as ContainerType
};