/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContainerLoadingMode = 'Fcl' | 'Lcl';

export const ContainerLoadingMode = {
    Fcl: 'Fcl' as ContainerLoadingMode,
    Lcl: 'Lcl' as ContainerLoadingMode
};