/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ContainerLength = 'Ft20' | 'Ft40' | 'Ft45';

export const ContainerLength = {
    Ft20: 'Ft20' as ContainerLength,
    Ft40: 'Ft40' as ContainerLength,
    Ft45: 'Ft45' as ContainerLength
};