/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * the dto used to send an error response to the client
 */
export interface ErrorResponse { 
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number;
    /**
     * the message for the error response
     */
    message?: string;
    /**
     * the collection of errors for the current context
     */
    errors?: { [key: string]: Array<string>; };
}