/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * the dto used to send an error response to the client when an unhandled exception occurs on the server
 */
export interface InternalErrorResponse { 
    /**
     * error status
     */
    status?: string;
    /**
     * http status code of the error response
     */
    code?: number;
    /**
     * the reason for the error
     */
    reason?: string;
    /**
     * additional information or instructions
     */
    note?: string;
}