/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PackageType = 'Bags' | 'Bales' | 'Boxes' | 'Drums' | 'Crates' | 'Units';

export const PackageType = {
    Bags: 'Bags' as PackageType,
    Bales: 'Bales' as PackageType,
    Boxes: 'Boxes' as PackageType,
    Drums: 'Drums' as PackageType,
    Crates: 'Crates' as PackageType,
    Units: 'Units' as PackageType
};