/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PortType = 'Sea' | 'Air' | 'Inland';

export const PortType = {
    Sea: 'Sea' as PortType,
    Air: 'Air' as PortType,
    Inland: 'Inland' as PortType
};