/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type QuotationRequestSortProperty = 'CreatedAtTimestamp' | 'CargoType' | 'TotalWeight' | 'IsPriorityShipment' | 'TransportationMode' | 'StartingLocationType' | 'FinalLocationType' | 'StartGeoLocationAddress' | 'FinalGeoLocationAddress' | 'StartPortName' | 'FinalPortName' | 'Status';

export const QuotationRequestSortProperty = {
    CreatedAtTimestamp: 'CreatedAtTimestamp' as QuotationRequestSortProperty,
    CargoType: 'CargoType' as QuotationRequestSortProperty,
    TotalWeight: 'TotalWeight' as QuotationRequestSortProperty,
    IsPriorityShipment: 'IsPriorityShipment' as QuotationRequestSortProperty,
    TransportationMode: 'TransportationMode' as QuotationRequestSortProperty,
    StartingLocationType: 'StartingLocationType' as QuotationRequestSortProperty,
    FinalLocationType: 'FinalLocationType' as QuotationRequestSortProperty,
    StartGeoLocationAddress: 'StartGeoLocationAddress' as QuotationRequestSortProperty,
    FinalGeoLocationAddress: 'FinalGeoLocationAddress' as QuotationRequestSortProperty,
    StartPortName: 'StartPortName' as QuotationRequestSortProperty,
    FinalPortName: 'FinalPortName' as QuotationRequestSortProperty,
    Status: 'Status' as QuotationRequestSortProperty
};