/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type QuoteStatus = 'Draft' | 'Pending' | 'Accepted' | 'Rejected' | 'Expired';

export const QuoteStatus = {
    Draft: 'Draft' as QuoteStatus,
    Pending: 'Pending' as QuoteStatus,
    Accepted: 'Accepted' as QuoteStatus,
    Rejected: 'Rejected' as QuoteStatus,
    Expired: 'Expired' as QuoteStatus
};