/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TransportationMode = 'Intermodal' | 'ByOcean' | 'ByAir' | 'ByRoad' | 'ByRail' | 'ByBarge';

export const TransportationMode = {
    Intermodal: 'Intermodal' as TransportationMode,
    ByOcean: 'ByOcean' as TransportationMode,
    ByAir: 'ByAir' as TransportationMode,
    ByRoad: 'ByRoad' as TransportationMode,
    ByRail: 'ByRail' as TransportationMode,
    ByBarge: 'ByBarge' as TransportationMode
};