/**
 * Forwarding Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Unit = 'Kg' | 'Ton' | 'Cbm' | 'Lt';

export const Unit = {
    Kg: 'Kg' as Unit,
    Ton: 'Ton' as Unit,
    Cbm: 'Cbm' as Unit,
    Lt: 'Lt' as Unit
};