//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forwarding.Management.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forwarding.Management.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both dimensions and volume values are present..
        /// </summary>
        public static string BothDimensionsAndVolumePresent {
            get {
                return ResourceManager.GetString("BothDimensionsAndVolumePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions should be null for a container with FCL loading mode..
        /// </summary>
        public static string DimensionsShouldBeNullIfFcl {
            get {
                return ResourceManager.GetString("DimensionsShouldBeNullIfFcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not suitable for property {0}..
        /// </summary>
        public static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message cannot be longer than {0} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string cannot be shorter than {0} characters..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port with the specified id does not exist..
        /// </summary>
        public static string PortWithSpecifiedIdDoesNotExist {
            get {
                return ResourceManager.GetString("PortWithSpecifiedIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quotation request with id &apos;{0}&apos; should have the status &apos;Pending&apos;..
        /// </summary>
        public static string QuotationRequestInPendingStatus {
            get {
                return ResourceManager.GetString("QuotationRequestInPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quotation request with id &apos;{0}&apos; should have the status &apos;Withdrawn&apos;..
        /// </summary>
        public static string QuotationRequestInWithdrawnStatus {
            get {
                return ResourceManager.GetString("QuotationRequestInWithdrawnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quotation request with id &apos;{0}&apos; should exist..
        /// </summary>
        public static string QuotationRequestShouldExists {
            get {
                return ResourceManager.GetString("QuotationRequestShouldExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} should be null or empty..
        /// </summary>
        public static string ShouldBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ShouldBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification should exist for cargo or item level..
        /// </summary>
        public static string SpecificationShouldExistForCargoOrItem {
            get {
                return ResourceManager.GetString("SpecificationShouldExistForCargoOrItem", resourceCulture);
            }
        }
    }
}
